In [1]:
import pandas as pd

In [5]:
pd.read_csv("data/F1_tweets.csv")[["date", "text", "source"]]

C:\Users\Michi\AppData\Local\Temp\ipykernel_14392\541402625.py:1: DtypeWarning: Columns (5,6,7,12) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv("data/F1_tweets.csv")[["date", "text", "source"]]

,date,text,source
0,2021-08-01 23:59:18,The next great #F1 duo!!! @ESPNF1 https://t.co...,Twitter for iPhone
1,2021-08-01 23:59:10,@F1 What if…Hamilton would have gone to the pi...,Twitter for iPhone
2,2021-08-01 23:58:48,This has been a tiring #f1 day... https://t.co...,Twitter for Android
3,2021-08-01 23:58:11,Valteri Bottass tracking down Max Verstappen o...,Twitter for iPhone
4,2021-08-01 23:57:40,No words to describe the #HungarianGP so I wil...,Twitter for iPhone
...,...,...,...
632383,2022-08-20 22:18:08,"""I like it. Its a very relaxed, more of a fami...",Twitter for Android
632384,2022-08-20 22:17:35,"""Fun"" fact:\nIn the last 8 races Charles finis...",Twitter Web App
632385,2022-08-20 22:16:05,[Reddit Formula Dank]\nBabe wake up new meme f...,podiumdb-app
632386,2022-08-20 22:11:04,@AlaricAloor @fogle_shane @psb_dc @DrJDrooghaa...,TweetDeck
632387,2022-08-20 22:10:27,Find it harder and harder to stay up late for ...,Twitter for Android

In [9]:
races = pd.read_csv("data/F1_stats/circuits.csv")[["circuitId","name","location","country"]]
races

,circuitId,name,location,country
0,1,Albert Park Grand Prix Circuit,Melbourne,Australia
1,2,Sepang International Circuit,Kuala Lumpur,Malaysia
2,3,Bahrain International Circuit,Sakhir,Bahrain
3,4,Circuit de Barcelona-Catalunya,Montmeló,Spain
4,5,Istanbul Park,Istanbul,Turkey
...,...,...,...,...
71,75,Autódromo Internacional do Algarve,Portimão,Portugal
72,76,Autodromo Internazionale del Mugello,Mugello,Italy
73,77,Jeddah Corniche Circuit,Jeddah,Saudi Arabia
74,78,Losail International Circuit,Al Daayen,Qatar
75,79,Miami International Autodrome,Miami,USA

In [21]:
drivers = pd.read_csv("data/F1_stats/drivers.csv")
drivers

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
849,851,aitken,89,AIT,Jack,Aitken,1995-09-23,British,http://en.wikipedia.org/wiki/Jack_Aitken
850,852,tsunoda,22,TSU,Yuki,Tsunoda,2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda
851,853,mazepin,9,MAZ,Nikita,Mazepin,1999-03-02,Russian,http://en.wikipedia.org/wiki/Nikita_Mazepin
852,854,mick_schumacher,47,MSC,Mick,Schumacher,1999-03-22,German,http://en.wikipedia.org/wiki/Mick_Schumacher
853,855,zhou,24,ZHO,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Guanyu_Zhou

In [27]:
results = pd.read_csv("data/F1_stats/results.csv")
results

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25655,25661,1086,825,210,20,13,16,16,16,0.0,69,\N,\N,37,15,1:23.511,188.856,11
25656,25662,1086,848,3,23,17,17,17,17,0.0,69,\N,\N,43,12,1:23.047,189.911,11
25657,25663,1086,849,3,6,19,18,18,18,0.0,69,\N,\N,60,8,1:22.478,191.221,11
25658,25664,1086,852,213,22,16,19,19,19,0.0,68,\N,\N,58,16,1:23.538,188.795,12
25659,25665,1086,822,51,77,8,20,20,20,0.0,65,\N,\N,60,19,1:24.002,187.752,131

In [33]:
driver_results = results.join(drivers, on="driverId", how='left', lsuffix='_left', rsuffix='_right')[["position","positionOrder","driverRef","circuitId"]]
driver_results

KeyError: "['circuitId'] not in index"

In [ ]:
from google.cloud import storage


def write_read(bucket_name, blob_name):

    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(blob_name)

    with blob.open("r") as f:
        print(f.read())